server:
  port: 8000

spring:
  config:
    import: aws-secretsmanager:resident_meeting

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/user/sign-up
            - Method=POST

        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/user/login
            - Method=POST

        - id: user-service
          uri: http://user-service:8080/actuator/**
          predicates:
            - Path=/api/user/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/api/user/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/user/**
          filters:
            - AuthorizationHeaderFilter

        - id: vote-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/vote/actuator/**, /api/agenda/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/api/vote/(?<segment>.*), /$\{segment}

        - id: vote-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/vote/**, /api/agenda/**
          filters:
            - AuthorizationHeaderFilter

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace

token:
  secret: ${token_secret}
  expiration: ${token_expiration}